[project]
name = "markdown-mcp"
version = "0.1.0"
description = "Pandoc-powered Markdown to Word MCP Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.11.1",
    "pypandoc>=1.13",
    "pytest>=8.4.1",
]
